on:
  push:
    branches:
      - main

name: Create Release

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: build
        run: ./gradlew build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/distributions/*.zip"
          draft: true
          allowUpdates: true
          tag: draft




#        id: release
#        with:
#          release-type: java
#      - name: Upload Release Artifact
#        if: ${{ steps.release.outputs.release_created }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: gh release upload ${{ steps.release.outputs.tag_name }} build/distributions/*.zip
